FROM maven:3.9-eclipse-temurin-21-alpine AS build

COPY . .

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-alpine

COPY --from=build /target/*.jar demoForm.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "demoForm.jar"]